import express from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import fs from 'fs';
import { GoogleGenAI } from '@google/genai';

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.get('/api/tools', (req, res) => {
    try {
      const configPath = path.resolve(process.cwd(), 'src/tools-config.json');
      const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      res.json(config.tools);
    } catch (error) {
      res.status(500).json({ error: 'Failed to load tools configuration' });
    }
  });

  app.post('/api/generate-tool', async (req, res) => {
    try {
      const { prompt, name, category, customApiKey } = req.body;
      if (!prompt || !name || !category) {
        return res.status(400).json({ error: 'Missing required fields' });
      }

      let ai = new GoogleGenAI({ apiKey: customApiKey || process.env.GEMINI_API_KEY });
      const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

      const systemInstruction = `
        Role: You are a Senior Product Manager, Frontend Architect, & SEO Specialist. Build a world-class, production-ready React component for the requested tool.
        1. Stealth Mode & "No-AI" Trace: Write clean, modular, human-like code. No "Generated by AI" comments. Use standard naming conventions (handleFileUpload, processData).
        2. Visual Balance (60:30:10 Rule): 60% White (#FFFFFF) backgrounds, 30% Slate (#1E293B) for typography and borders, 10% Indigo (#4F46E5) for interactive elements. Use "Flat Modern Light Display". Soft borders (1px solid #E2E8F0), extremely soft shadows (0 1px 2px rgba(0,0,0,0.05)).
        3. Technical Execution: Use browser-native APIs (Canvas, FileReader) or installed libraries (pdf-lib). No Node.js server-side code.
        4. Premium Live Preview (CRITICAL): If the tool involves visual changes (e.g., Image Compressor, PDF Merge, Watermark), you MUST implement a "Real-time Preview" window. For compressors/filters, use a "Comparison Slider" (Original vs Modified). For PDFs, show page thumbnails. This must feel like a premium product (like SmallPDF).
        5. Trust & UX: Add a "Security Badge" ("Files are processed locally. No data is stored."). Implement full-screen Drag & Drop overlays, Progress Bars, and "Copy to Clipboard" with Success Toasts.
        6. Security & Limits: Implement client-side file size checks (e.g., max 20MB) with professional error states ("File size exceeds the 20MB limit").
        7. Localization (Intl API): Automatically adapt dates, times, and currencies using Intl API.
        8. SEO & Content: Include a "How-To" guide (3-4 steps), a short SEO blog (technical, no fluff), and an FAQ section (Accordion style) at the bottom of the tool.
        9. Output: Return ONLY valid TSX code exporting a default React component. Use lucide-react for icons.
        The component should be self-contained and assume it is rendered inside a container with padding.
      `;

      let response;
      try {
        response = await ai.models.generateContent({
          model: 'gemini-3.1-pro-preview',
          contents: `Create a React component for a tool named "${name}". Description/Prompt: ${prompt}`,
          config: {
            systemInstruction,
            temperature: 0.2,
          }
        });
      } catch (err: any) {
        // If custom API key fails, fallback to platform key
        if (customApiKey && process.env.GEMINI_API_KEY) {
          console.log('Custom API key failed, falling back to platform key...');
          ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
          response = await ai.models.generateContent({
            model: 'gemini-3.1-pro-preview',
            contents: `Create a React component for a tool named "${name}". Description/Prompt: ${prompt}`,
            config: {
              systemInstruction,
              temperature: 0.2,
            }
          });
        } else {
          throw err;
        }
      }

      let code = response.text || '';
      // Extract code block if it exists
      const codeMatch = code.match(/```(?:tsx|ts|javascript|js)?\n([\s\S]*?)\n```/i);
      if (codeMatch && codeMatch[1]) {
        code = codeMatch[1];
      } else {
        code = code.replace(/^\\s*\`\`\`(tsx|ts|javascript|js)?\\n/i, '');
        code = code.replace(/\\n\`\`\`\\s*$/i, '');
      }

      const toolFilePath = path.resolve(process.cwd(), `src/tools/${slug}.tsx`);
      fs.mkdirSync(path.dirname(toolFilePath), { recursive: true });
      fs.writeFileSync(toolFilePath, code, 'utf-8');

      // Update config
      const configPath = path.resolve(process.cwd(), 'src/tools-config.json');
      const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      
      const existingIndex = config.tools.findIndex((t: any) => t.slug === slug);
      const newTool = { slug, name, description: prompt.substring(0, 100) + '...', category };
      
      if (existingIndex >= 0) {
        config.tools[existingIndex] = newTool;
      } else {
        config.tools.push(newTool);
      }
      
      fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');

      res.json({ success: true, tool: newTool });
    } catch (error: any) {
      console.error('Error generating tool:', error);
      res.status(500).json({ error: error.message || 'Failed to generate tool' });
    }
  });

  app.post('/api/social-download', async (req, res) => {
    try {
      const { url, platform } = req.body;
      if (!url) return res.status(400).json({ error: 'URL is required' });

      if (platform === 'instagram') {
        // Extract shortcode
        const match = url.match(/(?:instagram\.com\/(?:[^\/]+\/)?(?:p|reel|tv)\/)([^\/\?]+)/);
        const shortcode = match ? match[1] : null;
        
        if (!shortcode) {
          return res.status(400).json({ error: 'Invalid Instagram URL' });
        }

        const embedUrl = `https://www.instagram.com/p/${shortcode}/embed/captioned/`;
        let html = '';
        
        try {
          const response = await fetch(`https://api.allorigins.win/get?url=${encodeURIComponent(embedUrl)}&t=${Date.now()}`);
          if (!response.ok) throw new Error('Primary proxy failed');
          const data = await response.json();
          html = data.contents;
        } catch (e) {
          // Fallback proxy
          const fallbackResponse = await fetch(`https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(embedUrl)}`);
          if (!fallbackResponse.ok) throw new Error('Network error: Failed to fetch media');
          html = await fallbackResponse.text();
        }
        
        let extractedUrl = null;
        let isVideo = false;

        const videoMatch = html.match(/"video_url":"([^"]+)"/);
        if (videoMatch && videoMatch[1]) {
          extractedUrl = videoMatch[1].replace(/\\u0026/g, '&');
          isVideo = true;
        } else {
          const imageMatch = html.match(/"display_url":"([^"]+)"/);
          if (imageMatch && imageMatch[1]) {
            extractedUrl = imageMatch[1].replace(/\\u0026/g, '&');
          }
        }

        if (!extractedUrl) {
          return res.status(404).json({ error: 'Media not found. The post might be private or unsupported.' });
        }

        return res.json({ url: extractedUrl, type: isVideo ? 'video' : 'image' });
      }

      // Placeholder for other platforms
      return res.status(400).json({ error: 'Unsupported platform' });
    } catch (error: any) {
      console.error('Social download error:', error);
      res.status(500).json({ error: 'Failed to process URL' });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
